"""Phase 6 - Trust Circle and Risk Detection tables

Revision ID: phase6_trust_circle_risk
Revises: 20ac7135f306
Create Date: 2026-06-26 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'phase6_trust_circle_risk'
down_revision: Union[str, None] = '20ac7135f306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tables already exist, just alter them to match schema
    
    # Alter trust_circle_members: make phone NOT NULL, add default for alert_level
    op.alter_column('trust_circle_members', 'phone', nullable=False)
    op.alter_column('trust_circle_members', 'alert_level', server_default='concern')
    
    # Alter risk_scores: make scores nullable
    op.alter_column('risk_scores', 'isolation_score', nullable=True)
    op.alter_column('risk_scores', 'burnout_score', nullable=True)
    op.alter_column('risk_scores', 'distress_score', nullable=True)
    op.alter_column('risk_scores', 'crisis_probability', nullable=True)
    op.alter_column('risk_scores', 'overall_level', nullable=True)
    
    # Add index on scored_at for risk_scores
    op.create_index(op.f('ix_risk_scores_scored_at'), 'risk_scores', ['scored_at'], unique=False)
    
    # risk_monitoring_enabled already exists in user_profiles
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove risk_monitoring_enabled column from user_profiles
    op.drop_column('user_profiles', 'risk_monitoring_enabled')
    
    # Drop risk_scores table
    op.drop_index(op.f('ix_risk_scores_scored_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_user_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    
    # Drop trust_circle_members table
    op.drop_index(op.f('ix_trust_circle_members_user_id'), table_name='trust_circle_members')
    op.drop_table('trust_circle_members')
    
    # ### end Alembic commands ###
