"""Add settings column to users table

Revision ID: phase6_user_settings
Revises: phase5_notifications
Create Date: 2026-06-27 08:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'phase6_user_settings'
down_revision = 'phase5_notifications'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True, default=dict))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
