"""
AI System Prompts for SoulSync
"""

from .discovery import DISCOVERY_SYSTEM_PROMPT
from .companion import REGULAR_COMPANION_PROMPT
from .goal_coach import GOAL_COACH_SYSTEM_PROMPT
from .memory_extraction import MEMORY_EXTRACTION_PROMPT
from .insights import INSIGHT_GENERATION_PROMPT

__all__ = ['DISCOVERY_SYSTEM_PROMPT', 'REGULAR_COMPANION_PROMPT', 'GOAL_COACH_SYSTEM_PROMPT', 'MEMORY_EXTRACTION_PROMPT', 'INSIGHT_GENERATION_PROMPT']
